version: "3.8"

services:
  db:
    container_name: test_voch
    image: mysql:5.7.41
    env_file:
      - .env
    environment:
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - test_voch:/var/lib/mysql

volumes:
  test_voch:
